name: cornell-camp-sprint
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: cornell-camp-sprint
  id: ec66283b-0afa-4b2c-a884-34d4e999ee3e
services:
  appserver:
    overrides:
      services:
        environment:
            BEHAT_PARAMS: >-
              {
                  "extensions" : {
                      "Behat\\MinkExtension" : {
                          "base_url" : "http://nginx/"
                        }
                    }
                }
tooling:
  test:
    service: appserver
    cmd:
      - "robo"
      - "test"
  phpunit:
    service: appserver
    cmd:
      - "robo"
      - "unit"
  behat:
    service: appserver
    cmd:
      - "robo"
      - "behat"
  lint:
    service: appserver
    cmd:
      - "robo"
      - "lint"
